trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true

- task: UseDotNet@2
  displayName: Install .NET
  inputs:
    version: 6.0.x

- script: dotnet restore -v minimal src/VoltRpc.sln
  displayName: Restore Packages

- script: dotnet build src/VoltRpc.sln --no-restore -v minimal -c $(buildConfiguration)
  displayName: Build Project
  
- script: dotnet test src/VoltRpc.Tests/VoltRpc.Tests.csproj --logger trx
  displayName: Run Tests
  
- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: src/bin
    artifactName: NuGet-Packages