trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet restore -v minimal src/VoltRpc.sln
  displayName: Restore Packages

- script: dotnet build src/VoltRpc.sln --no-restore -v minimal -c $(buildConfiguration)
  displayName: Build Project
  
- script: dotnet test src/VoltRpc.Tests/VoltRpc.Tests.csproj --logger trx
  displayName: Run Tests
  
- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
