namespace VoltRpc.Proxy.Generator
{
    /// <summary>
    ///     Contains code and templates for proxy generation
    /// </summary>
    public static class ProxyCodeTemplates
    {
        private const string AutoGeneratedWarning =
            @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by VoltRpc.Proxy.Generator
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";

        private const string GenerateProxyAttributeNamespace = "VoltRpc.Proxy";
        private const string GenerateProxyAttributeClass = "GenerateProxyAttribute";

        public const string GenerateProxyAttributeOverrideName = "GeneratedName";

        public static readonly string GenerateProxyAttributeName =
            $"{GenerateProxyAttributeNamespace}.{GenerateProxyAttributeClass}";

        public static readonly string GenerateProxyAttributeCode = $@"{AutoGeneratedWarning}
using System;

namespace {GenerateProxyAttributeNamespace}
{{
    [AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
    public sealed class {GenerateProxyAttributeClass} : Attribute
    {{
        public GenerateProxyAttribute()
        {{
        }}

        public string {GenerateProxyAttributeOverrideName} {{ get; set; }}
    }}
}}";

        public static readonly string ProxyCodeTemplate = $@"{AutoGeneratedWarning}
using VoltRpc.Communication;

namespace VoltRpc.Proxy.Generated
{{{{
    public class {{0}} : {{1}}
    {{{{
        private readonly Client client;

        public {{0}}(Client client)
        {{{{
            this.client = client;
        }}}}
{{2}}
    }}}}
}}}}";
    }
}