namespace VoltRpc.Proxy.Generator;

/// <summary>
///     Contains code and templates for proxy generation
/// </summary>
public static class ProxyCodeTemplates
{
    private const string AutoGeneratedWarning =
        @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by VoltRpc.Proxy.Generator
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------";

    public const string GenerateProxyGeneratedDefaultNameSpace = "VoltRpc.Proxy.Generated";
    private const string GenerateProxyAttributeNamespace = "VoltRpc.Proxy";
    private const string GenerateProxyAttributeClass = "GenerateProxyAttribute";

    public const string GenerateProxyAttributeOverrideName = "GeneratedName";
    public const string GenerateProxyAttributeOverrideNamespace = "GeneratedNamespace";

    public static readonly string GenerateProxyAttributeName =
        $"{GenerateProxyAttributeNamespace}.{GenerateProxyAttributeClass}";

    public static readonly string ProxyCodeTemplate = $@"{AutoGeneratedWarning}
using VoltRpc.Communication;

namespace {{0}}
{{{{
    public class {{1}} : {{2}}
    {{{{
        private readonly Client client;

        public {{1}}(Client client)
        {{{{
            this.client = client;
        }}}}

{{3}}
    }}}}
}}}}";
}