//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoltRpc.Proxy.Generator {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VoltRpc.Proxy.Generator.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotAMethod {
            get {
                return ResourceManager.GetString("NotAMethod", resourceCulture);
            }
        }
        
        internal static string NotAMethodDescription {
            get {
                return ResourceManager.GetString("NotAMethodDescription", resourceCulture);
            }
        }
        
        internal static string MethodInvalidAccessibility {
            get {
                return ResourceManager.GetString("MethodInvalidAccessibility", resourceCulture);
            }
        }
        
        internal static string MethodInvalidAccessibilityDescription {
            get {
                return ResourceManager.GetString("MethodInvalidAccessibilityDescription", resourceCulture);
            }
        }
        
        internal static string InterfaceInvalidAccessibility {
            get {
                return ResourceManager.GetString("InterfaceInvalidAccessibility", resourceCulture);
            }
        }
        
        internal static string InterfaceInvalidaccessibilityDescription {
            get {
                return ResourceManager.GetString("InterfaceInvalidaccessibilityDescription", resourceCulture);
            }
        }
        
        internal static string ProxyNameBlank {
            get {
                return ResourceManager.GetString("ProxyNameBlank", resourceCulture);
            }
        }
        
        internal static string ProxyNameBlankDescription {
            get {
                return ResourceManager.GetString("ProxyNameBlankDescription", resourceCulture);
            }
        }
        
        internal static string ProxyNamespaceBlank {
            get {
                return ResourceManager.GetString("ProxyNamespaceBlank", resourceCulture);
            }
        }
        
        internal static string ProxyNamespaceBlankDescription {
            get {
                return ResourceManager.GetString("ProxyNamespaceBlankDescription", resourceCulture);
            }
        }
    }
}
